FROM python:3.12-alpine
WORKDIR /app

COPY requirements/requirements.txt requirements/requirements.txt

RUN pip install -r requirements/requirements.txt

COPY . .

CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8080"]